language: android
before_install: #1.1
- nvm install 6
- node --version
install: #1.2
- npm install
 - echo y | android update sdk -u -a -t tools
 - echo y | android update sdk -u -a -t platform-tools
 - echo y | android update sdk -u -a -t build-tools-26.0.1
 - echo y | android update sdk -u -a -t android-26
 - echo y | android update sdk -u -a -t extra-google-m2repository
 - echo y | android update sdk -u -a -t extra-android-m2repository
android: #1.3
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script: 
- cd android && ./gradlew assembleRelease #3
